---
suse-12.3:
  aarch64:
    sles12-sp3-pool:
      name: "SLES12-SP3-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP3:GA/SLES/12.3/POOL/aarch64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP3/aarch64/product"
      ask_on_error: false
    sles12-sp3-updates:
      name: "SLES12-SP3-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP3:aarch64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP3/aarch64/update"
      ask_on_error: false
    sle12-sp3-ha-pool:
      name: "SLE12-SP3-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP3:GA/sle-ha/12.3/POOL/aarch64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP3/aarch64/product"
      ask_on_error: false
    sle12-sp3-ha-updates:
      name: "SLE12-SP3-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP3:aarch64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP3/aarch64/update"
      ask_on_error: false
    suse-enterprise-storage-5-pool:
      name: "SUSE-Enterprise-Storage-5-Pool"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP3:Update:Products:SES5/ses/5/POOL/aarch64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/Storage/4/aarch64/product"
      ask_on_error: false
    suse-enterprise-storage-5-updates:
      name: "SUSE-Enterprise-Storage-5-Updates"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:5:aarch64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/Storage/5/aarch64/update"
      ask_on_error: false
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
  x86_64:
    sles12-sp3-pool:
      name: "SLES12-SP3-Pool"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP3:GA/SLES/12.3/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-SERVER/12-SP3/x86_64/product"
      ask_on_error: false
    sles12-sp3-updates:
      name: "SLES12-SP3-Updates"
      required: "mandatory"
      features: ["os"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-SERVER:12-SP3:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-SERVER/12-SP3/x86_64/update"
      ask_on_error: false
    sle12-sp3-ha-pool:
      name: "SLE12-SP3-HA-Pool"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP3:GA/sle-ha/12.3/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/SLE-HA/12-SP3/x86_64/product"
      ask_on_error: false
    sle12-sp3-ha-updates:
      name: "SLE12-SP3-HA-Updates"
      required: "optional"
      features: ["ha"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:SLE-HA:12-SP3:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/SLE-HA/12-SP3/x86_64/update"
      ask_on_error: false
    suse-enterprise-storage-5-pool:
      name: "SUSE-Enterprise-Storage-5-Pool"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsproduct://build.suse.de/SUSE:SLE-12-SP3:Update:Products:SES5/ses/5/POOL/x86_64"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Products/Storage/5/x86_64/product"
      ask_on_error: false
    suse-enterprise-storage-5-updates:
      name: "SUSE-Enterprise-Storage-5-Updates"
      required: "mandatory"
      features: ["ceph"]
      repomd:
        tag: "obsrepository://build.suse.de/SUSE:Updates:Storage:5:x86_64/update"
        fingerprint: "FEAB 5025 39D8 46DB 2C09 61CA 70AF 9E81 39DB 7C82"
      url:
      smt_path: "SUSE/Updates/Storage/5/x86_64/update"
    ptf:
      name: "PTF"
      required: "recommended"
      url:
      ask_on_error: false
